logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#[YouTube]
#build-mode = "module"
#arch = "arm64-v8a"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
#apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"

#[Music]
#build-mode = "module"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube.music/"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube.music/"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"


[Twitter]
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.twitter.android/"

[Twitch]
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
apkmonk-dlurl = "https://www.apkmonk.com/app/tv.twitch.android.app/"

[Reddit]
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.reddit.frontpage/"

[Messenger]
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.facebook.orca"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.facebook.orca/"

[Spotify]
build-mode = "module"
arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android/versions"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.spotify.music/"

[Instagram]
build-mode = "module"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.instagram.android/"

[Facebook]
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/facebook/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.facebook.katana/"

[Trakt]
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/trakt/trakt"
apkmonk-dlurl = "https://www.apkmonk.com/app/tv.trakt.trakt/"
